### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by seppo0010** [jonhoo/cucache-rust#2]
I have a similar project and I was trying to see how the networking layer works in rucache. I see that you have a thread pool of 200 threads handling connections, which is similar to my approach.

In my project, I run into a problem that increasing the number of clients reduces drastically the response time and I think it might be happening in rucache as well.

Running `memtier_benchmark` I got the following results.

| Ops/second | rucache | memcached |
| --- | --- | --- |
| 5 | 59099.61 | 64023.93 |
| 10 | 63139.02 | 66883.32 |
| 20 | 57882.29 | 68306.19 |
| 40 | 46186.77 | 72808.59 |

For rucache I had to restart the server before each test, otherwise the numbers were lower. I tried to run it with 80 clients and it just does not finish. Also the time distribution is a lot worse (several ops take a lot longer).

My theory is that the problem is to have many threads blocked in `TcpStream.read()`, but I'm not sure how to improve that with Rust. I'm just letting you know about this problem, and if you find a solution/improvement, I'll be happy to hear about it.

**Comment by jonhoo** [comment]
Hmm.. How many cores do you have for the server and the clients? Are you running 80 clients _per core_, or 80 in total?

I wrote [jonhoo/volley](https://github.com/jonhoo/volley) to try to benchmark exactly this behavior, and I'm finding that Rust doesn't seem to have any fundamental scaling problems for `TcpStream.read()` as far as I can tell.

**Comment by seppo0010** [comment]
I'm running in a VM with only one core, so it is both per core and in total. Does that explain the behavior?

**Comment by jonhoo** [comment]
With only a single core, these results are hard to interpret. If you have 80 clients, all the clients and server threads are sharing a single CPU, and interfering with each other. In addition, the context switching will kill performance too. To get representative results you should try running on more cores, and pin the server and client to different cores using `numactl` (or some other similar tool -- `taskset` might do).

**Comment by seppo0010** [comment]
I was actually interested in trying this because I have a similar project and I was having these results.

My project: https://github.com/seppo0010/rsedis/

The tool I'm using: https://github.com/antirez/redis/blob/unstable/src/redis-benchmark.c

In my machine (2 cores) the results are good up to 5 clients, and goes down from there. With 50 clients it can do about half ops/sec than with 1.

Is that the kind of results you expect?

If `TcpStream.read()` works well only when you have a few clients per core, I believe that is actually a scaling problem, considering memcached/redis can handle hundreds of clients per core.

**Comment by jonhoo** [comment]
My point is that with 50 clients, your _client_ also has to do more work, and if it shares cores with the server, then your performance will look like it's declining when it really isn't. If you look at the [benchmark results](https://github.com/jonhoo/volley/blob/master/benchmark/perf.png) in volley, you'll see that the Rust implementation (which uses `TcpStream.read()`) scales well to many cores, and is no less efficient than a C socket read.

**Comment by seppo0010** [comment]
Sorry, but I don't fully understand your point. I'm not trying to be hard on this.

I'm using the same client tool with the same number of clients in the same machine to compare `rucache` and `memcached`, and another tool (also keeping clients and machine constant) to compare `rsedis` with `redis`. In both cases I see how the Rust implementation deteriorates faster than the C implementation.

Doesn't that refute your point that the clients are the problem?

**Comment by seppo0010** [comment]
I think maybe we are focusing on different things. You are trying to see how much increase in ops/sec adding more cores has, while I'm trying to see how can I get more ops/sec with a low number of cores.

**Comment by jonhoo** [comment]
Ah, yes, you're right -- if all you care about is performance per core, it shouldn't matter that clients are sharing the cores if the C implementation is faster. However, I don't think the bottleneck is `TcpStream.read()`; the Volley results clearly show that Rust is, if anything, faster at reading from a network socket than C is (I have no idea why that is though). Have you tried profiling with valgrind or perf to figure out where your code is spending its time?

**Comment by seppo0010** [comment]
I have not, and I don't know how to do that. I might take a look later. I guess this issue can be closed because it is "as designed".
